### ISSUE TITLE
[Youtube] comments not working

### ISSUE THREAD

**Issue by wildman99** [tikservices/html5-video-everywhere#20] opened 2015-02-10 08:15 UTC
the comment section under youtube videos will not load with this addon enabled.

Workarounds until a proper solution is implemented:
- use ViewTube userscript as proposed by @andrewpros 
- use YouToube All HTML5 addon as proposed by @UhuruNUru

**Comment by pocesar** [comment] 2015-02-13 02:00
Watching the exception in Firebug, it seems that the youtube library (in base.js file) tries to make a query selection on "yt-uix-hovercard-target", and maybe it was removed, therefore throwing the exception and halting the script

**Comment by lejenome** [comment] 2015-02-13 07:00
1/ The extension blocks loading YouTube' html5player.js file which It seems needed to load comment section. To fix the problem, I need to re-implement the needed part of code from this file.
2/ @pocesar That's caused by blocking html5player.js and replacing `#player-mole-caintainer` content with Firefox video player.

**Comment by andrewpros** [comment] 2015-03-22 20:13
Any ETA on this?

**Comment by lejenome** [comment] 2015-03-23 08:30
@andrewpros not soon

**Comment by andrewpros** [comment] 2015-03-23 15:40
@lejenome 
Hmm.

If it is that problematic, maybe it is better to change how this add on works, leave html5player.js in place and just remove some DOM elements to prevent loading YT player, but maintaining the comments this way.

**Comment by andrewpros** [comment] 2015-04-01 15:28
@lejenome I want to add also that sometimes there is some bug, not sure why and how, but then both video and comments are working as expected.

**Comment by Mosrite** [comment] 2015-05-09 10:13
Could you maybe add an option to enable HTML5Everywhere for Youtube on third-party sites (where you won't see the comments anyway), but disable it on youtube.com itself?
This would at least be a temporary workaround until the actual issue is fixed.

**Comment by andrewpros** [comment] 2015-05-22 14:42
@lejenome 
I would suggest avoiding implementing comments from html5player.js back into addon  at any cost.

This is too difficult to make and maintain and YT can change anything, whenever they want, breaking functionality instantly.

In my opinion the best reliable option here is avoiding html5player file blocking, let it run and then just remove and replace the player.

**Comment by hrvstr** [comment] 2015-12-03 15:33
Will there be an update on this issue anytime soon? Or is too problematic to solve?

**Comment by lejenome** [comment] 2015-12-03 15:46
Didn't find a solution yet.
Patches are welcome

**Comment by sebma** [comment] 2015-12-07 00:42
Hi,
I ticked "Disable on Youtube", so that it displays the Youtube comments.
Is there any other workaround here ?

Seb.

**Comment by v-fox** [comment] 2016-02-19 03:44
As remedy I propose adding context menu option like "Reload page with original player", so it can be used after watching the video with proper player and gaining burning desire to comment. Disabling support completely is an overkill. In my case it's also dangerous, my FF started segfaulting with original Youtube player after recent Mozilla "fix" of 44.0.2.

**Comment by sebma** [comment] 2016-04-23 16:12
Luckily, I'm glad I couldn't install firefox 44.0.2, It's not in the Ubuntu repositories :)

Did you have time to study [andrewpros's proposal](https://github.com/lejenome/html5-video-everywhere/issues/20#issuecomment-104677741) ?

**Comment by andrewpros** [comment] 2016-05-05 17:51
I just gave up, it is easy to do, but the author don't want or can't do it, i just use ViewTube and everything works.

**Comment by UhuruNUru** [comment] 2016-06-03 20:08
Not a fix for this, but a workaround that works for users
Install YouTube All HTML5 Addon and disable this add on for YouTube.
Might help this addon maker fix his issue, it doesn't appear to use the built-in player though.

**Comment by andrewpros** [comment] 2016-06-04 14:29
Want help?

Just don't block html5player.js, remove and replace only the YT player object, i wanted to make something but i have issues with firefox in development mode, can't force it to use my version, so i can't test anything.

**Comment by danyz7** [comment] 2016-06-04 15:15
Not working

El jun 4, 2016 7:29 AM, andrewpros notifications@github.com escribió:

Want help?

Just don't block html5player.js, remove and replace only the YT player object, i wanted to make something but i have issues with firefox in development mode, can't force it to use my version, so i can't test anything.

##

**Comment by lejenome** [comment] 2016-06-04 15:25
I tried it before, it caused race conditions where YouTube default video player is running on the background with the addon video player especially when switching the video on same page.

**Comment by lejenome** [comment] 2016-06-04 15:36
@andrewpros did you try to set `xpinstall.signatures.required` to `false` on `about:config` ?

**Comment by andrewpros** [comment] 2016-06-04 16:03
I have the dev version of Firefox, so i can install whatever i want, this was not the issue, and now i can't really try again, i would say the documentation for developing addon is huge, but it is poor on the subject how to make it work, no matter what i tried, it wasn't using my local files, half a day of try & fail, so i quit.

Found out ViewTube, so i really can't help, but maybe check how ViewTube does it.

**Comment by andrewpros** [comment] 2016-06-04 16:07
@danyz7

Of course it will not work, it is a task for a developer, it won't be just like that, you block it and it will work, you need to change the way it works, replace things after html5player.js executed the parts you need and then remove the YT player, replace by html version.

**Comment by lejenome** [comment] 2016-06-04 16:14
I'm interested on ViewTube solution. I may even try to reuse the code as
much as possible because I may not be able to keep up with sites changes.

I can't promise any solution before next month because I have exams on
coming days.

**Comment by lejenome** [comment] 2017-09-27 15:25
This issue was fixed on latest release which is a complete rewrite of the extension to support new YouTube changes and Firefox WebExtension API

**Closed as completed by lejenome** 2017-09-27 15:25 UTC
Labels: bug, help wanted
