### ISSUE TITLE
youtube not showing comments or allowing votes

### ISSUE THREAD

**Issue by godfree2** [tikservices/html5-video-everywhere#58] opened 2015-07-10 15:48 UTC
addon is not allowing voting or viewing comments

**Comment by drselump14** [comment] 2015-10-04 02:52
same issue here

**Comment by vitusson** [comment] 2015-11-25 20:37
I can confirm this. After trying out a lot of of preference settings in my FF, with no comment section, I switched off single add-ons, and it turned out to be the HTML5 one. 
Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0

**Comment by vitusson** [comment] 2015-11-25 20:40
ah, now I see there's already a bug report https://github.com/lejenome/html5-video-everywhere/issues/20. Sorry, overlooked that one.

**Comment by lejenome** [comment] 2017-01-11 22:03
duplicate of https://github.com/lejenome/html5-video-everywhere/issues/20

**Closed as completed by lejenome** 2017-01-11 22:03 UTC
Labels: duplicate
